---
- name: install vagrant with yum or apt
  action: "{{backcompat_pkg_mgr}} name={{vagrant_url}}"
  sudo: yes
  register: result_install_vagrant
  until: result_install_vagrant|success
  when: backcompat_pkg_mgr == "yum" or backcompat_pkg_mgr == "apt"

# Handle dnf case for Fedora
- name: "check if vagrant exists"
  command: "rpm -q vagrant"
  changed_when: False
  ignore_errors: True
  register: package_exists_result
  when: package_names is defined and backcompat_pkg_mgr == "dnf"

# Use command since dnf was only added as a module in ansible 1.9.0
- name: install vagrant with dnf
  command: dnf install -y {{vagrant_url}}
  sudo: yes
  register: result_install_vagrant_dnf
  until: result_install_vagrant_dnf|success
  when: backcompat_pkg_mgr == "dnf" and package_exists_result|failed
